# Generated by Django 2.2.12 on 2023-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtspApp', '0005_auto_20230129_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='channel',
            field=models.CharField(choices=[('0', 'Atatürk Cad.'), ('1', 'Cumhuriyet Cadç'), ('2', 'Fatih Cad.'), ('3', 'Gül Cad.')], default='0', max_length=2),
        ),
    ]
