# Generated by Django 2.2.12 on 2023-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('0', 'sink_'), ('1', 'sink_'), ('2', 'sink_'), ('3', 'sink_'), ('4', 'sink_')], default='0', max_length=2)),
            ],
        ),
    ]
