# Generated by Django 2.2.12 on 2023-01-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtspApp', '0002_auto_20230129_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='channel',
            field=models.CharField(choices=[('1', 'file:///home/azu/Desktop/deepstream/works/task-3/add_del_source_django/rtspApp/cams/v1.h264'), ('2', 'file:///home/azu/Desktop/deepstream/works/task-3/add_del_source_django/rtspApp/cams/v2.h264'), ('3', 'file:///home/azu/Desktop/deepstream/works/task-3/add_del_source_django/rtspApp/cams/v3.h264'), ('4', 'file:///home/azu/Desktop/deepstream/works/task-3/add_del_source_django/rtspApp/cams/v4.h264'), ('5', 'file:///home/azu/Desktop/deepstream/works/task-3/add_del_source_django/rtspApp/cams/v5.h264'), ('6', 'file:///home/azu/Desktop/deepstream/works/task-3/add_del_source_django/rtspApp/cams/v6.h264')], default='1', max_length=2),
        ),
    ]
