# Generated by Django 2.2.12 on 2023-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtspApp', '0004_auto_20230129_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='channel',
            field=models.CharField(choices=[('1', 'Atatürk Cad.'), ('2', 'Cumhuriyet Cadç'), ('3', 'Fatih Cad.'), ('4', 'Gül Cad.'), ('5', 'Karanfil Cad.')], default='1', max_length=2),
        ),
    ]
